fivestars-os/aladdin

- commands/python/libs/aws/dns_mapping.py
This handles `Exception('Does not handle truncated hostedzone')`
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/route53.html#Route53.Paginator.ListResourceRecordSets
> [ALDN-94] Add pagination support

- Dockerfile
- aladdin-container.sh
- aladdin.sh
- commands/bash/container/bash/bash
- commands/bash/container/change-permissions/change-permissions
- commands/bash/container/clean/clean
- commands/bash/container/cluster/cluster
- commands/bash/container/create-namespace/create-namespace
- commands/bash/container/delete-namespace/delete-namespace
- commands/bash/container/get-dashboard-url/get-dashboard-url
- commands/bash/container/helm-history/helm-history
- commands/bash/container/host/host
- commands/bash/container/load-images/load-images
- commands/bash/container/save-images/save-images
- commands/bash/container/test-local/test-local
- commands/bash/container/test-remote/test-remote
- commands/bash/host/config/config
- commands/bash/host/env/env
- commands/bash/host/get-minikube-endpoints/get-minikube-endpoints
- commands/python/bash_help.json
- scripts/bash_profile.bash
> Add support for aws iam authenticator

- scripts/infra_k8s_check.sh
- @jcwilson saw benefits in cpu idle usage
> Upgrade minikube to 1.9.2

- aladdin.sh
[ALDN-166](https://fivestars.atlassian.net/browse/ALDN-166)
> [ALDN-166] Sync date and time automatically every time

- README.md
- aladdin.sh
Bare minimum changes to make software installation optional.
Not trying to refactor the bash script at this time.
[ISSUE-64](https://github.com/fivestars-os/aladdin/issues/64)
> [ISSUE-64] Allow option to skip installing software

- aladdin-container.sh
- scripts/bash_profile.bash
To close https://github.com/fivestars-os/aladdin/issues/50
> Fix AUTHENTICATION_ENABLED unbound variable bug

- commands/python/command/cluster_init.py
- commands/python/command/namespace_init.py
[ALDN-215](https://fivestars.atlassian.net/browse/ALDN-215)
> [ALDN-215] Add namespace parameter to release_exists() calls

- Dockerfile
- commands/python/command/cluster_init.py
- commands/python/command/deploy.py
- commands/python/command/namespace_init.py
- commands/python/command/publish.py
- commands/python/command/rollback.py
- commands/python/command/start.py
- commands/python/command/stop.py
- commands/python/command/undeploy.py
- commands/python/libs/k8s/helm.py
Release this after a few days assuming no regressions from the helm3 migration
> Remove helm2 completely

- Dockerfile
- pyproject.toml
This PR upgrades istioctl to 1.9.2, in order to upgrade istio
> Upgrade istioctl

- aladdin/commands/build.py
Only import built images to k3d if there are images to import
> Only import to k3d if there are images

- aladdin/commands/get_certificate.py
- aladdin/lib/arg_tools.py
- aladdin/lib/k8s/kubernetes.py
- aladdin/lib/k8s/kubernetes_utils.py
- pyproject.toml
This PR adds a `--wait` flag to the `get-certificate` command
Additionally it adds a util function to get the current namespace
> Add flag to enable waiting for a cert to be available

- aladdin.sh
- pyproject.toml
More info here: https://k3d.io/faq/faq/#solved-nodes-fail-to-start-or-get-stuck-in-notready-state-with-log-nf_conntrack_max-permission-denied
and here: https://k3d.io/faq/faq/#solved-nodes-fail-to-start-or-get-stuck-in-notready-state-with-log-nf_conntrack_max-permission-denied
> Add compatibility fix for K3D on newer linux kernels

- Dockerfile
- pyproject.toml
This PR updates [Poetry](https://python-poetry.org/) to the latest version
> Update Poetry to 1.1.10 (latest)

- .github/workflows/pull_request.yaml
- .github/workflows/release.yaml
- Dockerfile
This PR adds a workflow for building the docker image on pull requests to master.
In the future we could extend this workflow to do other checks such as: tests, formatting checks, etc
This PR also fixes a build issue missed in #101
> Add Github Actions Pull Request Workflow

- Dockerfile
> Make docker-compose executable

- aladdin/commands/deploy.py
- aladdin/commands/start.py
- pyproject.toml
This is an alternative to setting it via [aladdin-config](https://github.com/fivestars/aladdin-config/pull/50) - seems cleaner, but open to feedback if anyone has a preference
> INFRA-982: add service.clusterName

- aladdin/config.py
- aladdin/env.py
- aladdin/main.py
- pyproject.toml
This PR fixes the checks made when initially setting up aladdin and using the config command.
> Fix aladdin config command when setting up aladdin

- poetry.lock
- pyproject.toml
https://github.com/pallets/markupsafe/issues/284
Markupsafe v2.1.0 has a breaking change 😢
> Pin markupsafe to v2.0.1

- aladdin/commands/helm_values.py
- aladdin/lib/git.py
- pyproject.toml
This PR is a small improvement to the `helm-values` command so that aladdin can skip the "clone" and "checkout" steps if possible
> Skip clone and checkout repository in helm-values command

- aladdin/commands/helm_values.py
- aladdin/lib/project_conf.py
- pyproject.toml
This PR is a small improvement for the `helm-values` command when called from the current directory of the chart we want to use
> Try to use current chart for helm-values command

- Dockerfile
- pyproject.toml
This PR updates the python and poetry version installed in the aladdin container image
> Update python & poetry in container image

- Dockerfile
- pyproject.toml
- scripts/infra_k8s_check.sh
Fixes issue on aws/aws-iam-authenticator side with upgraded helm
> Downgrade helm

- Dockerfile
> Upgrade istio from 1.14.6 to 1.16.4

- Dockerfile
I looked over the changelog and there did not seem to be any breaking changes
> Update Helm to v3.12.0

- .github/workflows/release.yaml
Reverts fivestars-os/aladdin#196
> Revert "fix: Update release"
