fivestars-os/aladdin

aladdin.sh
Bash functions should not call `exit`. This runs the risk of exiting the calling shell, not just
the function. This change ensures the safety of the function and maintains existing intended
functionality.
=> Use return rather than exit to leave function early

commands/python/command/deploy.py
The f-string prefix needs to be applied to each line in a multiline string.
=> Fix deploy warning msg and convert it to an error

README.md, aladdin.sh, scripts/install_nfs_mounts.sh
Aladdin uses minikube for local development which is a VirtualBox-based VM. Internally it mounts your `/Users` (or `/cygdrive/c/Users` for Cygwin users) directory to the root of the minikube filesystem. We have discovered that the `vboxsf` mounts are not as performant as NFS mounts and furthermore are not as reliable when it comes to detecting file changes made from the host. To address this, we replace the `vboxsf` mounts within minikube with NFS mounts.
=> Add a script to replace /Users with nfs mount

Dockerfile, README.md, aladdin-container.sh, aladdin.sh, commands/python/command/deploy.py, commands/python/main.py
* Add the `-i` shorthand for the `--init` command-line option 
* Add the `--image` command-line option to allow one to specify the aladdin image to use for
aladdin commands
* Avoid the need for `chmod 6000` on our host's `.ssh/config` file by mounting the hosts `~/.ssh`
directory at `/root/_ssh` and copying the directory to `/root/.ssh` when the container starts.
This way the ownership is transferred to the `root` user.
* Exit with an error code if the deploy command fails the "master branch" check
* Use simplified `apk add` functionality to avoid cache bloat
=> Various improvements

commands/python/requirements.txt
- It is not directly used
- awscli doesn't use the vulnerable pyyaml method as well: https://github.com/aws/aws-cli/issues/3828
=> Remove pyyaml from requirements

commands/python/command/connect.py
Under some circumstances (at least when a pod has been evicted), pod.status.container_statuses will be None and not enumerable.  We don't check for this, so if any pod is in such a state, running `aladdin connect` without arguments will fail and not allow specifying a deployment to connect to.  This PR catches that case.
[ALDN-126](https://fivestars.atlassian.net/browse/ALDN-126)
=> [ALDN-126] Don't fail to enumerate pods when some are Failed

Dockerfile, README.md, aladdin.sh, commands/bash/host/config/config, scripts/infra_k8s_check.sh
This PR updates aladdin to allow running natively on the host's docker
if available, by setting the new minikube.vm_driver preference in
~/.aladdin/config/config.json to 'none' (the default is 'virtualbox').
This also adds a 'minikube.memory' preference to allow configuring
the minikube VM's memory, if applicable.
[ALDN-130](https://fivestars.atlassian.net/browse/ALDN-130)
=> [ALDN-130] Allow running minikube with vm-driver=none

aladdin-container.sh
We don't need to validate AWS credentials when working in minikube (ie. LOCAL development). One may not have even defined their `~/.aws/credentials` or `~/.aws/config` files yet, but still want to
try out some local behavior.
[ALDN-147](https://fivestars.atlassian.net/browse/ALDN-147)
=> [ALDN-147] Only check AWS credentials when performing cluster operations

aladdin-container.sh, aladdin.sh, commands/bash/container/add-aws-assume-role-config/add-aws-assume-role-config, commands/python/bash_help.json, scripts/bash_profile.bash, scripts/shared.sh
High level:
- There will require an accompanying aladdin-config PR, that specifies which bastion account to use, and different roles we can assume (role that has sufficient privileges to run all aladdin command).
- Then, during aladdin's startup, we will now configure the ~/.aws/config and ~/.aws/credentials files to have the temporary credentials that are issued when calling `aws sts assume-role` for a given profile. 
- Users will now only be required to have aws config/creds file for the bastion account
=> Add assume role capabilities when bastion account is enabled

aladdin-container.sh
The regex we use to replace e.g. /Users/ptr/.minikube with /root/.minikube
was overly greedy, swallowing up path components that it shouldn't.  It
wasn't a problem while client.key and client.crt were in the top level of
.minikube/, but more recent minikube puts them in
.minikube/profiles/minikube, where aladdin now can't find them.
This commit updates the regex to just replace the path components up
to .minikube/ .
=> [ALDN-157] Fix regex for copying kube config into aladdin container

aladdin-container.sh
The new kube config regex didn't work, and didn't account for windows
paths.
[ALDN-157](https://fivestars.atlassian.net/browse/ALDN-157)
=> [ALDN-157] Fix newly broken kube config regex

commands/python/command/cmd.py, commands/python/libs/k8s/kubernetes.py, commands/python/project/project_conf.py
The `commands-base:2.0.0` image moves the `command.py` script to a new location and name:
`/usr/local/bin/aladdin_command`. It also assumes responsibility for ensuring that it is executable so
aladdin can just invoke the script or program. This is to allow developers to mount their host files
into their command containers at `/code` without stomping on this necessary script.
Projects that wish to move to the new `commands-base:2.0.0` image should update their commands'
Dockerfiles to derive from this image. Aladdin will check for the existence of an executable named
`aladdin_command` on the `PATH` before falling back to the previous behavior.
If one wishes to use an alternative implementation of the command script provided by
`commands-base:2.0.0`, one only needs to create an executable …
=> Add support for commands-base:2.0.0

commands/python/command/build.py, commands/python/project/project_conf.py
This change lets one provide extra arguments to the build script specified
in the `lamp.json` file. This can be useful during development if your build
takes a relatively long time and you want to only perform a partial build.
=> Pass extra args through to build command

README.md, aladdin.sh, scripts/infra_k8s_check.sh
Cygwin users require that their `~/.ssh` directory be copied into the minikube VM to avoid
file permission issues. We only need to copy the SSH keys once, not every time aladdin is
invoked, so we now move this to the `init` procedure. The copying process has also been updated to be more resilient to repeated invocations.
Since NFS usage is an optimization and can cause issues of its own, it's now behind a default-disabled aladdin config, `nfs`. Anyone depending on it will need to `aladdin config set nfs 1` to re-enable this behavior.
=> Disable NFS mounts by default and optimize copying of SSH keys into minikube

aladdin.sh
The `vm-driver` setting is deprecated, yet still functional, in minikube.
Users that upgrade and pick up this change should run the following command to move the
configuration to the expected location:
```
mk_driver=$(minikube config get vm-driver) \
&& minikube config set driver "$mk_driver" \
&& minikube config unset vm-driver
```
=> Switch to use minikube 'driver' setting instead of 'vm-driver'

lib/build-components/build_components/templates/python/Dockerfile.j2, lib/build-components/build_components/templates/python/macros.j2
We need to do the `chown` before switching the `USER`.
[ALDN-192](https://fivestars.atlassian.net/browse/ALDN-192)
=> [ALDN-192] Fix chown of WORKDIR to USER when publishing

.gitignore, Dockerfile
This adds:
* the Datawire helm repository to `helm` to enable deploying the Ambassador edge stack
* `edgectl` [(link)](https://www.getambassador.io/docs/latest/topics/using/edgectl/edge-control/) for managing an Ambassador API gateway
[ALDN-189](https://fivestars.atlassian.net/browse/ALDN-189)
=> [ALDN-189] Add edge tools to aladdin image

commands/python/command/deploy.py, commands/python/command/restart.py, commands/python/command/rollback.py, commands/python/command/start.py, commands/python/command/stop.py, commands/python/command/undeploy.py, commands/python/helm_rules.py, commands/python/libs/k8s/helm.py, commands/python/project/project_conf.py, docs/deploy_cmd.md, docs/restart_cmd.md, docs/rollback_cmd.md, docs/start_cmd.md, docs/stop_cmd.md, docs/undeploy_cmd.md
In some situations, a project may need to maintain two or more charts. `aladdin start`, `aladdin publish`
and `aladdin deploy` all currently support an all-or-nothing approach to their respective operations.
We should be able to specify which chart we wish to deploy.
This adds the `--chart` option to the `deploy', 'restart', 'rollback', 'start', 'stop', and 'undeploy' commands.
The default behavior for `start`, `stop` and `restart` is to perform the operation on all charts if not
otherwise specified. For the others, it will default to using the project's name (which prior to this was a
hard-coded assumption) and will only ever use a single chart per invocation. Multiple invocations are
required to deploy multiple charts.
This also adds the `.Values.project.name` and …
=> [ALDN-193] Support deploying a specific chart in a project

aladdin.sh
When I use cluster name like docker-desktop, it fails with 
```
jq: error: desktop/0 is not defined at <top-level>, line 1:
.cluster_aliases.docker-desktop
jq: 1 compile error
```
This PR is to fix that problem.
https://github.com/fivestars-os/aladdin/issues/63
=> [ISSUE-63] Allow cluster name with dashes

README.md, aladdin.sh
minikube commands are executed with direct calls to `minikube`
and with helper function.
When --no-manage-minikube is set:
1. direct calls to `minikube` become no op.
2. helper function return right away if MANAGE_MINIKUBE is false
This change might seem hacky. But  aladdin.sh will have to be
rewritten first to make it easy to make these types of changes.
[ISSUE-66](https://github.com/fivestars-os/aladdin/issues/66)
=> [ISSUE-66] Option to ask aladdin to not manage minikube

aladdin.sh, commands/bash/container/bash/bash, scripts/bash_cmd_includes.bash, scripts/bash_cmd_init.bash
This allows one to provide a command to `aladdin bash` and have it run directly in the aladdin
container instead of having to wait for the shell prompt and type it in there.
[ALDN-204](https://fivestars.atlassian.net/browse/ALDN-204)
=> [ALDN-204] Allow command to be provided directly to aladdin bash

commands/bash/container/bash/bash
The recently-added direct `aladdin bash` command invocation functionality did not provide support
for adopting the intended permissions available to other aladdin commands and tools like `kubectl`.
This wraps the provided command with `with_aladdin_perms_wrapper` when invoking it directly in a
bash shell, thus providing the requisite permissions for the duration of the command.
[ALDN-205](https://fivestars.atlassian.net/browse/ALDN-205)
=> [ALDN-205] Use with_aladdin_perms_wrapper for direct aladdin bash commands

Dockerfile, aladdin-container.sh, commands/bash/container/delete-namespace/delete-namespace, commands/python/command/cluster_init.py, commands/python/command/deploy.py, commands/python/command/namespace_init.py, commands/python/command/publish.py, commands/python/command/rollback.py, commands/python/command/start.py, commands/python/command/stop.py, commands/python/command/undeploy.py, commands/python/libs/k8s/helm.py, scripts/infra_k8s_check.sh
During the helm3 migration, we will have aladdin commands use helm3, but have support for helm2. Once everything has been confirmed to migrate over, we will remove tiller, and remove helm2 support from aladdin.
=> Use helm3 in aladdin commands with fallback helm2 option

Dockerfile, README.md
This PR updates the "Installation" section of the README. It also adds `ssh` back in, this go inadvertently removed when changing base Docker image and is needed for connecting to github using ssh (for commands like `publish`)
=> Add ssh to Dockerfile and update installation steps

aladdin/lib/k8s/helm.py, docs/create_aladdin_configuration.md
This PR adds support for a `values.yaml` file in `aladdin-config`, it provides the same functionality as the `"values"` key in `config.json`, however a yaml file provides more flexibility in the data types that are supported and how the data is structured.
=> Add support for cluster config values

aladdin/__init__.py, poetry.lock, pyproject.toml
[urllib3](https://pypi.org/project/urllib3/#history) (1.26.0) released a new version today 11/10 and package version resolution is unable to resolve for the previous version.
Giving this error on installation:
```
requests 2.24.0 requires urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you'll have urllib3 1.26.0 which is incompatible.
botocore 1.19.15 requires urllib3<1.26,>=1.25.4; python_version != "3.4", but you'll have urllib3 1.26.0 which is incompatible.
```
=> Add urllib3 to pyproject.toml

.githooks/lib/trufflehog-excluded.txt, .gitignore, aladdin.sh, docs/troubleshooting.md
Mounting the host's `.ssh` directory into the aladdin container at `/root/.ssh` can be problematic
due to ssh's strict requirements regarding file permissions for that directory.
Docker volume mounts set their uid and gid to the host user's uid/gid values. This makes it
difficult for the `root` user to have access to these files without using setuid/setgid tricks, and
in some cases even that is insufficient.
These changes allow a host running an ssh agent with active identities to give the aladdin container
access to the agent by mounting the `SSH_AUTH_SOCK` file. The container's ssh client can then
communicate over the mounted socket, thus eliminating the need to mount the `.ssh` directory into
the container at all.
The behavior will be to default to the `.ssh` directory mount, but …
=> [ALDN-220] Enable ssh agent access in aladdin container

aladdin.sh
This PR adds a case statement to set specific `SSH_OPTIONS` for macos
=> Fix SSH Agent Forwarding for Mac OS

.github/workflows/release.yaml, Dockerfile, aladdin/lib/k8s/helm.py, pyproject.toml
This adds building an `arm64` flavored image - this means aladdin now has native support for the Mac M1 chipset 🥳
=> Add cross-platform image builds

aladdin/lib/k8s/helm.py, docs/create_aladdin_configuration.md, pyproject.toml
This PR fixes a small bug in the helm lib `find_values()` function. The path in aladdin-config should be constructed using the `CLUSTER_CODE` which is guaranteed to be correct.
=> Fix aladdin-config path when retrieving values.yaml

aladdin-container.sh, aladdin/bash/container/add-aws-assume-role-config/add-aws-assume-role-config, aladdin/bash/container/create-namespace/create-namespace, pyproject.toml
Extended the `create-namespace` command to slap on a label/tag with the id (from AWS) of the person that created the namespace; this will make it easier when removing potentially orphaned namespaces
=> Attach label to namespace, to aid in owner identification

Dockerfile
This PR adds the [docker-compose](https://docs.docker.com/compose/) CLI to the aladdin container. Although aladdin targets kubernetes specifically `docker-compose` can also be used as a build tool, because of the well-defined `docker-compose.yml` config file users can declaratively define the images that need to be built without the need to define custom scripts for aladdin to execute.
Example:
```yaml
x-common-args: &common-args
HASH: "${HASH:-local}"
version: '3.8'
services:
base:
image: "my-service-base:${HASH:-local}"
build:
context: docker
dockerfile: base.Dockerfile
api:
image: "my-service-api:${HASH:-local}"
build:
context: .
dockerfile: docker/api.Dockerfile
args:
<<: *common-args
web:
image: "my-service-web:${HASH:-local}"
build:
context: .
dockerfile: docker/web.Dockerfile
``` …
=> Add docker-compose to aladdin container

README.md, aladdin-container.sh, aladdin.sh, aladdin/bash/container/cluster/cluster, aladdin/config.py, aladdin/lib/cluster_rules.py, aladdin/main.py, docs/cluster_cmd.md, pyproject.toml
This PR adds a new "user" config option called "config_repo". 
This new config option should be set to the repository where the user has their `aladdin config`. Aladdin will then ensure that this repo is always checked out and up to date before running any command. The config repo is expected to be tagged in a similar manner to aladdin, so that aladdin and config tags always match.
=> Use repository for aladdin config

README.md, aladdin.sh, aladdin/config.py, aladdin/env.py, aladdin/main.py, config-example/config.json, docs/create_aladdin_configuration.md, pyproject.toml
This PR updates aladdin to use the current package version to pull the corresponding docker image. This ensures that the host code and the container code are always in sync, otherwise there could be breaking changes between the two.
=> Use aladdin image matching current version

Dockerfile, aladdin/env.py, pyproject.toml
This PR updates kOps version to 1.21.1
Additionally it fixes a `FileNotFoundError` error when loading the aladdin user config
=> Update kOps to 1.21.1

aladdin-container.sh, aladdin/env.py, aladdin/lib/k8s/kubernetes.py, pyproject.toml, scripts/install-aladdin.sh
Trying to automatically inject `repo` values into the user aladdin config can result in a value with a duplicated prefix, example: `"plugin_repo": "git@github.com:git@github.com:fivestars/aladdin-plugins.git"`.
This PR adds a workaround to prevent that
=> Avoid duplicate repo prefix

.github/workflows/release.yaml, Dockerfile, aladdin/bash/container/create-namespace/create-namespace, aladdin/commands/cluster_init.py, aladdin/commands/deploy.py, aladdin/commands/get_certificate.py, aladdin/commands/namespace_init.py, aladdin/commands/rollback.py, aladdin/commands/start.py, aladdin/commands/stop.py, aladdin/commands/sync_dns.py, aladdin/commands/sync_ingress.py, aladdin/commands/undeploy.py, aladdin/config.py, aladdin/lib/aws/certificate.py, aladdin/lib/aws/dns_mapping.py, aladdin/lib/cluster_rules.py, aladdin/lib/utils.py, aladdin/main.py, pyproject.toml, scripts/install-aladdin.sh
This PR fixes two bugs:
- `create-namespace` plugin throws an error when we are unable to get an owner using awscli
- A hosted zone is not setup correctly when it is created by the `get-certificate` command
=> Fix namespace creation label & hosted zone delegation

aladdin/lib/cluster_rules.py, pyproject.toml
This PR adds a fix for running aladdin in python < 3.8, `cached_property` was only added to `functools` until python 3.8, so we need a backport in order to support python 3.7
=> Add backport for cached property

aladdin.sh, poetry.lock, pyproject.toml
This PR adds an error message if `docker info` reports that it using cgroups v2. The current image of `k3s` we are using is only compatible with v1
=> Add check for cgroups v2

aladdin/bash/container/cluster/cluster, aladdin/bash/container/create-namespace/create-namespace
1. Fix the permanent error from aladdin:
`Error from server (AlreadyExists): namespaces "default" already exists`
2. Keep aladdin output dry
=> Make namespace creation declarative

aladdin-container.sh, pyproject.toml
This PR adds a small check to make sure the existing aws config does not already have a profile named like the one aladdin is trying to add
=> Add check for conflicting profiles in aws config

aladdin/commands/deploy.py
Small fix from after #122 , when the deploy function is called from `namespace_init()` or `cluster_init()` without specifying a chart
=> Fix deploy function when chart is not specified

aladdin/commands/start.py
The "start" command/function is missing the `"deploy.imageTag"` value after #122
=> Fix missing "deploy.imageTag" value in start command

aladdin-container.sh, aladdin/commands/start.py, pyproject.toml
This PR fixes the missing "deploy.ecr" value override in the "start" command
Additionally it fixes the usage of the "SSH_AUTH_SOCK" env var which may not always be set
=> Override "deploy.ecr" value in start command & use empty "SSH_AUTH_SOCK"

aladdin/commands/deploy.py, aladdin/commands/helm_values.py, aladdin/commands/start.py, aladdin/lib/cluster_rules.py, aladdin/lib/k8s/helm.py, pyproject.toml
This PR enables a new aladdin config option called `values_files`.
This new option will allow clusters to declare a list of values files that should be picked up from a project helm chart, previously this was inferred from the `cluster_name` config option.
=> Add support for multiple values file paths

aladdin.sh, scripts/shared.sh
This PR adds graceful handling of `ALADDIN_CONFIG_DIR` not being set in some of the initialization scripts in aladdin
Closes: #143
=> Fix `ALADDIN_CONFIG_DIR` not set

Dockerfile, pyproject.toml
- Bump up kops from 1.23.4 to 1.24.5
- Bump up kubectl from 1.23.10 to 1.24.10
=> Bump up kops and kubectl

Dockerfile, pyproject.toml
- Upgrade Kubernetes from 1.25 to 1.26
- Upgrade kOps from 1.26 to 1.28
=> Upgrade Kubernetes from 1.25 to 1.26

aladdin/commands/deploy.py, aladdin/commands/helm_values.py, aladdin/commands/publish.py, aladdin/lib/git.py, aladdin/lib/k8s/helm.py, aladdin/lib/publish_rules.py, config-example/config.json, docs/create_aladdin_configuration.md, poetry.lock, pyproject.toml
This PR removes the dependency on S3 helm charts, both during publish and deployment.
Additionally this PR cleans up how git repos are cloned and checked out
=> feat: Remove helm chart s3 publishing

aladdin/charts/merger/templates/values.yaml, aladdin/lib/publish_rules.py, pyproject.toml
This PR adds support for injecting dynamic values into other existing values for a helm chart.
For example this input values file
```yaml
tags:
owner: me
deploy:
imageTag: v1.0.0
aladdin.overlay:
tags:
imageTag: "{{ .Values.deploy.imageTag }}"
```
would get transformed into:
```yaml
tags:
owner: me
imageTag: v1.0.0
```
=> feat: Add support for value overlays

aladdin/charts/merger/templates/values.yaml, pyproject.toml
This PR allows treating values files as a template, for example:
```yaml
image:
tag: '{{ .Values.global.imageTag }}'
global:
imageTag: main
aladdin:
templateValues: true
```
would result in:
```yaml
image:
tag: 'main'
global:
imageTag: main
aladdin:
templateValues: true
```
=> feat(helm-values): Add templating of values

aladdin/commands/helm_values.py, aladdin/lib/project_conf.py, pyproject.toml
This PR adds new optional functionality to inject the `deploy.imageTag` value into new helm value locations depending on chart needs
The functionality can be turned on by adding `globalImageTag` to the lamp.json or by specifying a list of aliases as `imageTagAlias` in lamp.json
=> feat: Add support for image tag injection

.github/workflows/release.yaml, pyproject.toml
Current version does separation by comma: `--tag index.docker.io/fivestarsos/aladdin:1.30.10.5,--tag index.docker.io/fivestarsos/aladdin:latest` , but we need by space:
`--tag index.docker.io/fivestarsos/aladdin:1.30.10.5 --tag index.docker.io/fivestarsos/aladdin:latest`
=> fix: Update tags
